### ISSUE TITLE
Inquiry about the Removal of the PISO Solver and Guidance on its Reuse

### ISSUE THREAD

**Issue by degun89** [mianzhi/fosolvers#6]
I am writing this issue to seek some information and guidance related to the PISO solver. From the commit history, I noticed that at some point in the past, the PISO solver was removed and transitioned to the coupled solver.

Could you share the reasons that led to the removal of the PISO solver? Additionally, I am interested in using the PISO solver for my project. I would highly appreciate it if you could provide some guidance or suggestions on how I might be able to reintegrate or reuse the PISO solver within the current framework.

Thank you in advance for your time and assistance. Your expertise and advice are greatly appreciated.

**Comment by mianzhi** [comment]
hi, Thank you very much for your interest in this project and sorry for missing your message. I removed the PISO solver because I've never made it work. The current solvePBC() + solveEnergy() with outer iteration turned out to be more straightforward and more effective than my failed PISO attempt. For now I'm retaining the fragments of solveFull() because it's also more effective than my PISO attempt, but less effective than solvePBC() + solveEnergy(), at least for low Mach application that I'm more interested in with this solver.

This project has been idle for quite long but I'm planning on resuming the development in 2025. I might start with adding a simple transport property correlation. Then maybe Smagorinsky (I know it's not even close from reasonable LES but Smagorinsky might be the simplest turbulence closure model). Prism and pyramid will be added once I got better with GMSH meshing. Along the process I'll try to fix/improve the core solver as much as possible.

Please feel free share any comments and suggestions. Thanks again for your interest and looking forward for more discussion with you on CFD and PIC.

Best regards,
Mianzhi
